# Generated by Django 4.2.11 on 2026-05-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, help_text='Upload banner image directly.', null=True, upload_to='banners/')),
                ('image_url', models.URLField(blank=True, help_text='Or paste an external image URL (used if no image is uploaded).')),
                ('cta_text', models.CharField(blank=True, max_length=100, verbose_name='Button Text')),
                ('cta_url', models.CharField(blank=True, max_length=500, verbose_name='Button URL')),
                ('position', models.CharField(choices=[('hero', 'Hero Slider'), ('promo_top', 'Top Promotional Banner'), ('promo_mid', 'Mid-Page Promotional Banner'), ('sidebar', 'Sidebar Banner'), ('footer', 'Footer Banner')], default='hero', max_length=20)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, help_text='Leave blank to start immediately.', null=True)),
                ('valid_to', models.DateTimeField(blank=True, help_text='Leave blank to never expire.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['position', 'sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage (%)'), ('FIXED', 'Fixed Amount ($)'), ('FREE_SHIPPING', 'Free Shipping')], default='PERCENTAGE', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, help_text='Percentage value (0–100) or fixed dollar amount.', max_digits=10)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum cart total required to apply this code.', max_digits=10)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount cap for percentage codes. Leave blank for no cap.', max_digits=10, null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited uses.', null=True)),
                ('uses_count', models.PositiveIntegerField(default=0, editable=False)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Promo Code',
                'verbose_name_plural': 'Promo Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_bar_text', models.CharField(default='🔥 Big Sale Live! Get Up to 40% OFF on All Products.', help_text='Text shown in the top announcement bar across the store.', max_length=500)),
                ('announcement_bar_is_active', models.BooleanField(default=True, help_text='Toggle the announcement bar on/off.')),
                ('announcement_bar_link', models.URLField(blank=True, help_text='Optional click-through URL for the announcement bar.')),
                ('announcement_bar_bg_color', models.CharField(default='#111111', help_text='Background colour (hex, e.g. #111111).', max_length=20)),
                ('announcement_bar_text_color', models.CharField(default='#ffffff', help_text='Text colour (hex, e.g. #ffffff).', max_length=20)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=50.0, help_text='Minimum order total for free shipping. Set 0 for always-free.', max_digits=10)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.TextField(blank=True, help_text='Comma-separated keywords.')),
                ('is_maintenance_mode', models.BooleanField(default=False, help_text='Put the store in maintenance mode (non-staff see a notice).')),
                ('maintenance_message', models.TextField(blank=True, default="We're currently performing some maintenance. We'll be back shortly!")),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('tiktok_url', models.URLField(blank=True)),
                ('support_email', models.EmailField(blank=True, default='support@hexashop.com', max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
