# Generated by Django 4.2.11 on 2026-05-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Clothing/product image displayed in the hero circle on the home page.', null=True, upload_to='hero/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image_alt',
            field=models.CharField(blank=True, default='Featured collection', help_text='Alt text for the hero image (accessibility).', max_length=200),
        ),
    ]
