# Generated by Django 4.2.11 on 2026-07-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_settings', '0003_banner_hero_slide_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero Asset',
                'verbose_name_plural': 'Hero Assets',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Admin-facing label for this slide (e.g. "Ethnic Grace").', max_length=120)),
                ('document', models.JSONField(blank=True, default=dict, help_text='Full versioned slide schema (background, badge, title, subtitle, description, promo, buttons, image reference).')),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
