# Generated by Django 4.2.11 on 2026-05-14 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='size',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to use product base price', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. "Sky Blue", "Charcoal"', max_length=60)),
                ('hex_code', models.CharField(blank=True, default='', help_text='CSS hex colour e.g. #87CEEB — used as swatch when no image', max_length=7)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('image', models.ForeignKey(blank=True, help_text='Optional colour-specific product photo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='color_display', to='products.productimage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='products.product')),
            ],
            options={
                'db_table': 'product_colors',
                'ordering': ['sort_order', 'id'],
                'unique_together': {('product', 'name')},
            },
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='products.productcolor'),
        ),
    ]
