# Generated by Django 4.2.11 on 2026-07-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_migrate_variant_attrs_to_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='blur_data',
            field=models.TextField(blank=True, default='', help_text='Tiny base64 LQIP data-URI shown blurred while the real image loads. Generated automatically by the Celery image pipeline.'),
        ),
    ]
